### ISSUE TITLE
Java error: "Menubar cannot be resolved to a type"

### ISSUE THREAD

**Issue by Wooopz** [Lecerof/TelemetryViewer#1]
Hello, 
When i try to launch your program through Eclipse, i get this error in the Problems tab :
**"Menubar cannot be resolved to a type"	Main.java	/Telemetry Viewer/src	line 38.**

Maybe Menubar is a Missing library ?

Thank you.

**Comment by Lecerof** [comment]
Menubar is a class, but ill look in to it asap and get back to you. Meanwhile, did you do a clean clone of the project and cleaned the project in eclipse? Are you using the latest version of eclipse?

**Comment by Wooopz** [comment]
Ok. I have done a clean clone, i cleaned the project and it works like a charm !
I was able to save the layout in binary mode now.
Thank you very much :)

**Comment by Lecerof** [comment]
Perfect! You are very welcome. If you have any requests on functionality you want added you may open an issue again at any moment.

PS. Do not try to save a layout where you did not attach an input to the chart. It will give you headaches.
