### ISSUE TITLE
Error:(160, 30) java: incompatible types: WidgetDataset cannot be converted to javax.swing.JPanel

### ISSUE THREAD

**Issue by mjs513** [Lecerof/TelemetryViewer#8]
Figured I start new issues.  When I tried compiling on windows 10 using JRE 1.8.0_74 I am getting the error in your dial and quartenion chart files.

Not sure how to proceed?

**Comment by Lecerof** [comment]
You cant, its a bug. Ill fix it asap, but have no time now. For now you can either use farrells version or avoid the dial and quarternion charts. Using eclipse you can still run the program but with errors.

**Comment by mjs513** [comment]
Ok - will do - just wanted to check if it was different that the one posted.  I'll close this one.  You don't need two.
